name: sky130hd_temp-sense-generator

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
