name: sky130hd_temp-sense-generator

on:
  # push:
  #   branches:
  #   - main
  # pull_request:
  workflow_dispatch:

jobs:
  tempSense-sky130hd:
    runs-on: self-hosted
    steps:

      - name: Clone this repo
        uses: actions/checkout@v2

      - name: Clone OpenFASOC repo
        run: |
          mkdir $GITHUB_WORKSPACE/openfasoc && cd $GITHUB_WORKSPACE/openfasoc
          git clone https://github.com/saicharan0112/OpenFASOC && cd OpenFASOC


      - name: Run regression
        run: |
          cp $GITHUB_WORKSPACE/utils/run_regression.sh $GITHUB_WORKSPACE/openfasoc/OpenFASOC/.
          cd $GITHUB_WORKSPACE/openfasoc/OpenFASOC/ && chmo 755 run_regression.sh
          ./run_regression.sh     


      # - name: Build csv file and push changes
      #   run: |
      #     mkdir $GITHUB_WORKSPACE/data -p
      #     cp -rf $GITHUB_WORKSPACE/../3_head_6_inv $GITHUB_WORKSPACE/data/.
      #     chmod 755 $GITHUB_WORKSPACE/utils/build_csv.py
      #     cd $GITHUB_WORKSPACE/utils
      #     python3 ./build_csv.py
      #     cd $GITHUB_WORKSPACE
      #     git status
      #     git config --global user.name 'sai charan'
      #     git config --global user.email 'saicharan0112@users.noreply.github.com'
      #     git add -A 
      #     git commit -m "add run data"
      #     git push