name: sky130hd_temp-sense-generator

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run and test the tempSense generator
        env:
                IMAGE_NAME: msaligane/openfasoc:stable
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/idea-fasoc/OpenFASOC
          cd OpenFASOC
          touch file.log
          echo $PWD
          docker run --rm \
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              ls -al
              pip3 install -r requirements.txt &&\
              cd ./openfasoc/generators/temp-sense-gen &&\
              make sky130hd_temp\
            " | tee -a file.log
            if grep "\[ERROR\]" file.log; then exit 1; else exit 0; fi
