name: tempsense

on:
  # push:
  #   branches:
  #   - main
  # pull_request:
  workflow_dispatch:


jobs:
  generate:
    runs-on: self-hosted
    steps:

      - name: Clone this repo
        uses: actions/checkout@v2

      - name: Clone OpenFASOC repo
        run: |
          mkdir $GITHUB_WORKSPACE/openfasoc && cd $GITHUB_WORKSPACE/openfasoc
          git clone https://github.com/idea-fasoc/OpenFASOC && cd OpenFASOC


      - name: Run the generator and build gds, verilog, reports and spice decks
        run: |
          cd $GITHUB_WORKSPACE/regression && python3 run_regression.py tempsense generate

  simulate:
    runs-on: self-hosted
    needs: generate
    steps:

      - name: Run simulations by sweeping input parameters defined inside the config file under configuration directory
        run: |
          cd $GITHUB_WORKSPACE/regression
          docker run --rm -v $HOME:$HOME -e USER=$USER -w $PWD openfasoc_ci_image:latest bash -c "pip install pyyaml && python3 run_regression.py tempsense simulate"

  process:
    runs-on: self-hosted
    needs: [generate, simulate]
    steps:

      - name: Process the results using the simulation log files and extract results
        run: |
          cd $GITHUB_WORKSPACE/regression && python3 run_regression.py tempsense process

  # clean:
  #   runs-on: self-hosted
  #   if: always()
  #   needs: [generate, simulate, process]
  #   steps:
    
  #     - name: Clean the root privilages folder
  #       run: sudo rm -rf $GITHUB_WORKSPACE/*